spring:
  profiles:
    active: local

---

spring:
  profiles:
    active: dev
  resources:
    static-locations: classpath:/static/
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: lsDemo
  servlet:
    multipart:
      file-size-threshold: 1MB
      max-file-size: 100MB
      max-request-size: 100MB
  devtools:
    livereload:
      enabled: true

springbootwebfluxjjwt:
  password:
    encoder:
      secret: mysecret
      iteration: 33
      keylength: 256
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    expiration: 28800

server:
  port: 8080

resource:
  location: D:/Temp/
  uri_path: /img

google:
  map:
    api:
      endpoint: https://maps.googleapis.com/maps/api/geocode/json?
      key: AIzaSyCHAwUClWx7mNOxFrd-jCMzEpNpft4DVVQ

---

spring:
  profiles:
    active: prod